import type { Metadata } from "next";
import "./globals.css";
import {Raleway }from 'next/font/google'

const raleway = Raleway({
  variable: "--font-raleway",
  subsets:['latin'],
  display:"swap",
  weight: ['400', '700'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
